services:
  - type: web
    name: africapositiva
    runtime: static
    region: frankfurt
    branch: main
    autoDeployTrigger: commit
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
