import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { SafetyNote } from "@/components/site";
import { blogPosts } from "@/data/blogPosts";
export function generateStaticParams(){return blogPosts.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=blogPosts.find(x=>x.slug===slug);return p?{title:p.title,description:p.excerpt}:{};}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=blogPosts.find(x=>x.slug===slug);if(!p)notFound();return <article><header className="bg-cream py-20"><div className="container-site max-w-4xl"><Link href="/noticias" className="text-sm font-bold text-orange-700"><ArrowLeft className="mr-2 inline h-4 w-4"/>Notícias</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.15em] text-orange-700">{p.category} • {p.read}</p><h1 className="mt-5 font-display text-4xl font-semibold leading-tight sm:text-6xl">{p.title}</h1><p className="mt-6 text-xl leading-8 text-stone-600">{p.excerpt}</p></div></header><div className="container-site max-w-3xl py-16"><p className="text-lg leading-8 text-stone-700">Este artigo é um conteúdo editorial inicial, preparado para futura gestão através de um CMS. As exigências e procedimentos podem mudar; confirma sempre a informação junto das autoridades competentes.</p>{["Antes de começar","Organiza a informação","Confirma os requisitos atuais","Protege os teus dados"].map((h,i)=><section key={h} className="py-7"><h2 className="font-display text-2xl font-semibold">{h}</h2><p className="mt-4 leading-8 text-stone-600">Cada processo deve ser analisado de acordo com o objetivo, o país de origem, o destino e a situação individual. Guarda cópias, confirma prazos e utiliza apenas canais oficiais.</p></section>)}<SafetyNote/><Link href="/contactos" className="mt-8 inline-flex rounded-full bg-orange-500 px-6 py-4 text-sm font-bold text-white">Pedir orientação <ArrowRight className="ml-2 h-4 w-4"/></Link></div></article>;}
